name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

permissions:
  contents: read
  
jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@a7138bd426a25e8472abf4e8b37f2ab9f09c866a # main
